import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const cinzel = localFont({
  src: "./fonts/CinzelDecorative-Bold.ttf",
  variable: "--font-cinzel",
});

const muli = localFont({
  src: "./fonts/Muli-Regular.ttf",
  variable: "--font-muli",
});
export const metadata = {
  title: "Executives Diary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${muli.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
