import localFont from "next/font/local";
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";


const cinzel = localFont({
  src: "../fonts/CinzelDecorative-Bold.ttf",
  variable: "--font-cinzel",
});

const muli = localFont({
  src: "../fonts/Muli-Regular.ttf",
  variable: "--font-muli",
});
export const metadata = {
  title: "Executives Diary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}